'use strict';
(()=>{
const E=FootballEngine,app=document.getElementById('app'),STORE='this-life-football-v2';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let game=null,archives=[],legacy=[],screen='home',tab='season',playerTab='attributes',leagueCountry='KR',styleCategory='전체',seasonView='training',saveOK=true,pendingDeletion=null,pendingImport=null;
let reducedMotion=false;try{reducedMotion=JSON.parse(localStorage.getItem('football-life-preferences')||'null')?.reducedMotion||false}catch{}
let draft={name:'',number:9,pos:'ST',foot:'right',tactic:'balanced',focus:[]},deck=[],selected=0,revealed=false,rerolls=2;
const freshSeed=()=>{try{return crypto.getRandomValues(new Uint32Array(1))[0]}catch{return Date.now()^(Math.random()*0xffffffff)}};
try{const v=JSON.parse(localStorage.getItem(STORE)||'null');if(v?.version===2){game=v.game;archives=v.archives||[];legacy=v.legacy||[]}else{const old=JSON.parse(localStorage.getItem('this-life-football-v1')||'null');if(old)legacy=[...(old.archives||[]),...(old.game?[old.game]:[])].filter(Boolean)}}catch{saveOK=false}
{let changed=E.migrate(game);for(const g of archives)changed=E.migrate(g)||changed;if(changed)save()}
function save(){try{localStorage.setItem(STORE,JSON.stringify({version:2,game,archives,legacy}));saveOK=true;return true}catch{saveOK=false;return false}}
function toast(msg){let el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2800)}
const btn=(text,action,extra='',cls='primary')=>'<button class="'+cls+'" data-action="'+action+'" '+extra+'>'+text+'</button>';
const badge=(text,cls='')=>'<span class="badge '+cls+'">'+esc(text)+'</span>';
const sectionNames={'CHAPTER 02':'2 / 3','CHAPTER 03':'3 / 3',PLAYER:'선수',CAREER:'커리어',LEAGUE:'리그',MEMORIES:'기록','NEW STORY':'새 커리어','END OF CAREER':'은퇴','NEXT CHAPTER':'진학', 'TRANSFER WINDOW':'계약'};
const title=(small,big,desc='')=>'<div class="section-title"><span class="eyebrow">'+esc(sectionNames[small]||small)+'</span><h2>'+esc(big)+'</h2>'+(desc?'<p>'+esc(desc)+'</p>':'')+'</div>';
const bar=(value,cls='')=>'<div class="bar '+cls+'"><i style="width:'+E.clamp(value,0,100)+'%"></i></div>';
const windowLabel=t=>E.date(t).month===7?'여름 이적시장':'겨울 이적시장';
const money=v=>v>=10000?(v/10000).toFixed(1)+'억 원':Math.round(v).toLocaleString()+'만 원';
const foot=p=>p.foot==='left'?'왼발':'오른발';
const attrName=E.attributeName;
const rating=p=>p.apps?(p.ratingSum/p.apps).toFixed(2):'—';
const metric=(label,value)=>'<div class="metric"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong></div>';
function nav(){
 const items=[['home','홈','home'],['hub','커리어','career'],['player-menu','선수','player'],['archives','기록','records'],['settings','설정','settings']];
 return '<nav class="bottom-nav" aria-label="주 메뉴">'+items.map(([action,label,icon])=>{const active=action==='home'?screen==='home':action==='hub'?screen==='hub'&&tab!=='player':action==='player-menu'?screen==='hub'&&tab==='player':screen===action;return btn(menuIcon(icon)+'<span>'+label+'</span>',action,'aria-label="'+label+'" '+(active?'aria-current="page"':''),'nav-btn '+(active?'active':''));}).join('')+'</nav>';
}
function header(){if(!game)return'';const p=game.player;return'<header class="player-header"><button data-action="home" class="home-button" aria-label="홈으로">⌂</button><div class="identity"><b>'+esc(p.name)+'</b><span>'+esc(E.stageName(game))+' · '+E.POS[p.pos].name+' · '+game.age+'세</span></div><div class="overall"><small>종합 능력</small><b>'+E.overall(p)+'</b></div></header><nav class="tabs" aria-label="커리어 메뉴">'+[['season','시즌'],['career','커리어'],['player','선수'],['league','리그 / 우승']].map(([id,label])=>btn(label,'tab','data-value="'+id+'"','tab '+(tab===id?'active':''))).join('')+'</nav>'}
function home(){
 const active=game&&!game.retired;
 return '<main class="home" aria-label="축구 생활 메인"><img class="home-art" src="'+FootballHomeArt.src+'" width="'+FootballHomeArt.width+'" height="'+FootballHomeArt.height+'" alt="" aria-hidden="true" decoding="async" fetchpriority="high"><div class="home-top"><span class="home-edition">FOOTBALL LIFE<br><small>선수 커리어 게임</small></span>'+btn(menuIcon('settings'),'settings','aria-label="설정"','home-button')+'</div><div class="home-brand"><div class="brand-ball" aria-hidden="true">⚽</div><h1><span>축구</span><strong>생활</strong></h1><div class="brand-english">FOOTBALL LIFE</div></div><p class="home-story">2000년, 중3의 첫 킥오프.<br>나만의 축구 인생이 시작된다.</p><div class="home-actions">'+(active?btn('▷ '+esc(game.player.name)+'의 커리어 계속 →','hub','','big-start continue'):'')+btn('새로운 축구 인생 시작 →','new','','big-start '+(active?'secondary':''))+'<div class="home-quick">'+btn('선수 기록','archives','','quick-button')+btn('게임 안내','guide','','quick-button')+'</div>'+btn('<span>공지</span><b>경기 기록 · 성장 업데이트</b><i aria-hidden="true">›</i>','notice','','home-notice')+'</div></main>';
}
function creation(){
 return '<main><header class="story-header"><div class="header-row"><div><h1>축구 생활</h1><span class="english">FOOTBALL LIFE</span></div>'+btn('홈','home','','outline light')+'</div><p>2000년, 중학교 3학년.<br>첫 유니폼을 입을 준비를 해보자.</p></header><form id="creation" class="form-card">'+title('1 / 3','선수 만들기','15세의 선수로 시작합니다.')+btn('랜덤 생성','random','','outline random')+'<div class="field-grid"><label>이름<input id="name" name="name" maxlength="16" required placeholder="선수 이름" autocomplete="off" value="'+esc(draft.name)+'"></label><label>등번호<input id="number" name="number" type="number" min="1" max="99" value="'+draft.number+'" required></label></div><fieldset><legend>주발</legend><div class="grid two">'+[['right','오른발'],['left','왼발']].map(([id,t])=>btn(t,'draft','data-key="foot" data-value="'+id+'" aria-pressed="'+(draft.foot===id)+'"','choice '+(draft.foot===id?'selected':''))).join('')+'</div><p class="help">약한 발은 소속팀 훈련으로 익힐 수 있습니다.</p></fieldset><fieldset><legend>포지션</legend><div class="grid three">'+Object.entries(E.POS).map(([id,p])=>btn(p.name+'<small>'+id+'</small>','draft','data-key="pos" data-value="'+id+'" aria-pressed="'+(draft.pos===id)+'"','choice '+(draft.pos===id?'selected':''))).join('')+'</div></fieldset><section class="start-random"><h3>첫 소속은 랜덤 배정</h3><div class="start-odds"><div><b>99%</b><span>국내 중학교 10곳</span></div><div><b>1%</b><span>해외 구단 유스</span></div></div><details class="disclosure"><summary>시작 학교 보기</summary><ul class="school-pool">'+E.START_SCHOOLS.map(s=>'<li><b>'+s.name+'</b><span>'+s.basis+'</span></li>').join('')+'</ul></details></section><button class="primary" type="submit">다음 · 재능 후보 →</button></form></main>';
}
function abilityMeter(p,[id,name,desc]){const value=Math.floor(p.details[id]),tone=value>=80?'excellent':value>=65?'strong':value>=50?'developing':'emerging';return'<div class="ability-meter '+tone+'" data-stat="'+id+'"><div class="ability-label"><span title="'+esc(desc)+'">'+name+'</span><div><b>'+value+'</b><small>/ 99</small></div></div><div class="ability-track" role="meter" aria-label="'+name+'" aria-valuemin="0" aria-valuemax="99" aria-valuenow="'+value+'"><i style="width:'+(value/99*100).toFixed(2)+'%"></i></div></div>'}
function abilitySheet(p){
 const definitions=Object.fromEntries(Object.values(E.ATTR).flatMap(group=>group.items.map(item=>[item[0],item])));
 const sections=E.POSITION_ATTRIBUTES[p.pos].map(section=>{
  const meters='<div class="ability-grid">'+section.keys.map(id=>abilityMeter(p,definitions[id])).join('')+'</div>';
  if(section.collapsed)return'<details class="ability-section ability-other" data-group="other-'+p.pos+'" data-ability-group="'+section.id+'"><summary><span>기타 능력치</span><span class="ability-count">'+section.keys.length+'개</span><span class="ability-chevron" aria-hidden="true">⌄</span></summary>'+meters+'</details>';
  return'<section class="ability-section" data-ability-group="'+section.id+'"><div class="ability-heading"><h3>'+section.name+'</h3><span>'+section.keys.length+'개</span></div>'+meters+'</section>';
 }).join('');
 return'<div class="ability-sheet"><p class="ability-intro">'+(p.pos==='GK'?'골키퍼 전용 5개와 공용 12개를 역할별로 나눴습니다.':'공용 17개를 '+E.POS[p.pos].name+'의 역할에 맞춰 나눴습니다.')+'</p>'+sections+(p.pos==='GK'?'<p class="help ability-note"><b>반응속도</b>는 경기 상황에 대응하는 능력, <b>GK 반응속도</b>는 슈팅에 반응하는 능력입니다.</p>':'')+'</div>';
}
function talentNote(p){const t=E.talent(p);return'<div class="talent-note"><span class="eyebrow">타고난 재능</span><div class="row"><h3>'+t.name+'</h3>'+badge(t.short,p.talentId==='ambidextrous'?'teal':'blue')+'</div><p>'+t.desc+'</p></div>'}
function candidateScreen(){const c=deck[selected];return'<main><header class="simple-header">'+btn('← 선수 정보','edit','','outline')+'<b>'+esc(draft.name)+' · '+E.POS[draft.pos].name+'</b></header><div class="content">'+title('CHAPTER 02','재능 후보 3명','재능과 현재 능력치를 비교하세요.')+'<div class="talent-grid">'+deck.map((p,i)=>btn('<span class="card-number">0'+(i+1)+'</span>'+(revealed?'<strong>'+esc(p.label)+'</strong><small class="candidate-effect">'+E.talent(p).short+'</small><span>종합 능력 <b>'+E.overall(p)+'</b></span>':'<strong class="mystery">?</strong><span>아직 발견하지 못한 재능</span>'),'candidate','data-index="'+i+'" aria-pressed="'+(selected===i&&revealed)+'"','talent-card '+(selected===i&&revealed?'selected':''))).join('')+'</div>'+(revealed?'<section class="card candidate-report"><div class="row"><h3>스카우트 리포트</h3>'+badge('잠재력 '+c.potential)+'</div>'+talentNote(c)+abilitySheet(c)+'<p class="help">잠재력은 성장 한계의 기준입니다. 훈련과 출전 경험에 따라 도달하는 수준이 달라집니다.</p></section>'+btn('이 후보로 진행 →','growth'):'<div class="notice center">세 가지 재능이 기다리고 있습니다.</div>'+btn('3개 모두 열기','reveal'))+'<div class="row below">'+btn('재능 10종 살펴보기','talent-guide','','text-button')+btn('다시 뽑기 '+rerolls+'/2','reroll',(rerolls===0?'disabled':''),'outline')+'</div><p class="help">다시 뽑으면 재능 조합과 능력치를 새로 생성합니다.</p></div></main>'}
function attributes(){
 const p=game.player,weights=Object.entries(E.OVERALL_WEIGHTS[p.pos]).sort((a,b)=>b[1]-a[1]);
 return '<section class="card attribute-summary"><div class="row"><div><span class="eyebrow">현재 능력</span><h3>'+E.POS[p.pos].name+'</h3></div><div class="attribute-overall"><small>종합 능력</small><strong>'+E.overall(p)+'</strong></div></div>'+talentNote(p)+'<details class="disclosure overall-help"><summary>종합 능력 계산</summary><p class="help">'+E.POS[p.pos].name+'에게 중요한 능력일수록 더 크게 반영합니다. 컨디션과 체력은 경기 능력에 따로 적용됩니다.</p><div class="weight-list">'+weights.map(([id,w])=>'<span>'+attrName(id)+' <b>'+(w*100).toFixed(1)+'%</b></span>').join('')+'</div></details></section><section class="card attribute-report">'+abilitySheet(p)+'</section>';
}
function archetypePanel(){
 const p=game.player,a=E.ARCH[p.archetypeId],lv=E.level(p);
 return '<section class="archetype-hero"><span class="eyebrow">아키타입 · Lv.'+lv+'</span><h2>'+a.name+'</h2><b>'+a.plain+'</b><p>'+a.desc+'</p><div>주요 능력 <strong>'+a.keys.map(attrName).join(' · ')+'</strong></div></section><section class="card"><div class="row"><h3>아키타입 경험치</h3><b>'+p.axp.toLocaleString()+'</b></div>'+bar(lv===20?100:(p.axp%200)/2)+'<p class="help">'+(lv===20?'최고 레벨에 도달했습니다.':'다음 레벨까지 '+(200-p.axp%200)+' 경험치 · 출전과 훈련으로 성장합니다.')+'</p><div class="milestones">'+[['항상','능력치 조건 충족 → 기본 플레이스타일 자동 획득',true],['Lv.5','대표 플레이스타일+ 강화 1칸 개방',lv>=5],['Lv.10','강화 2칸 · 아키타입 전문화 선택 개방',lv>=10]].map(([l,t,on])=>'<div class="'+(on?'done':'')+'"><b>'+l+'</b><span>'+t+'</span></div>').join('')+'</div></section>'+plusPanel();
}
function requirementsHTML(p,requirements){
 return '<div class="requirements">'+requirements.map(([key,min])=>{const value=p.details[key],met=value>=min;return '<div class="requirement '+(met?'met':'')+'"><div><span>'+attrName(key)+'</span><b>'+Math.floor(value)+' <small>/ '+min+'</small></b></div><div class="requirement-track"><i style="width:'+Math.min(100,value/min*100).toFixed(1)+'%"></i></div><small>'+(met?'✓ 충족':Math.ceil((min-value)*10)/10+' 더 성장')+'</small></div>'}).join('')+'</div>';
}
function plusPanel(){
 const p=game.player,lv=E.level(p),capacity=E.plusCapacity(p),chosen=p.plusChoices||[],can=['ready','market'].includes(game.phase)&&!game.retired;
 return '<section class="card plus-section"><div class="row"><h3>플레이스타일+ 강화</h3>'+badge(chosen.length+' / '+capacity+'칸','gold')+'</div><p class="help">'+E.ARCH[p.archetypeId].name+'의 강화 경로입니다. 기본 특성을 획득하고 레벨·능력치 조건을 모두 채우면 직접 선택할 수 있습니다.</p><div class="plus-options">'+E.plusOptions(p).map(o=>{const selected=chosen.includes(o.id),learned=p.unlocked.includes(o.style),met=E.meets(p,o.requirements),ready=lv>=o.level&&learned&&met,full=chosen.length>=capacity,label=selected?'강화 해제 · 칸 반환':lv<o.level?'레벨 '+o.level+' 필요':!learned?'기본 플레이스타일 획득 필요':!met?'능력치 성장 필요':full?'강화 칸 사용 중':'플레이스타일+ 선택';return '<details class="plus-option disclosure '+(selected?'selected':'')+'" name="plus-path" data-group="plus-'+o.id+'"><summary><span><small>'+esc(o.name)+'</small><b>'+E.STYLES[o.style].name+'<em>+</em></b></span>'+badge(selected?'적용 중':ready?'선택 가능':'Lv.'+o.level,selected?'gold':'')+'</summary><p>'+E.STYLES[o.style].desc+'</p>'+requirementsHTML(p,o.requirements)+btn(label,'upgrade-plus','data-value="'+o.id+'" aria-pressed="'+selected+'" '+(!can||!selected&&(!ready||full)?'disabled':''),selected?'outline full':'primary')+'</details>'}).join('')+'</div><p class="help">레벨 5에 1칸, 10에 2칸이 열립니다. 선택한 +는 기본 효과를 더 강화합니다. 소속팀 화면에서 해제하고 다른 경로를 선택할 수 있습니다.</p></section>';
}
function trainingStyles(){
 const p=game.player,next=E.availableStyles(p).filter(s=>!p.unlocked.includes(s.id)).sort((a,b)=>E.styleProgress(p,b.id)-E.styleProgress(p,a.id)).slice(0,3);
 return '<section class="card training-styles"><div class="row"><h3>다음 플레이스타일</h3>'+badge('자동 적용 '+p.unlocked.length+'개','teal')+'</div><p class="help">획득에 가까운 특성입니다. 항목을 펼치면 필요한 능력치를 확인할 수 있습니다.</p>'+next.map(st=>'<details class="style-progress disclosure" name="next-style" data-group="target-'+st.id+'"><summary><span>'+styleIcon(st.id)+'<b>'+st.name+'</b></span>'+badge('조건 '+st.requirements.filter(([key,min])=>p.details[key]>=min).length+' / '+st.requirements.length)+'</summary><p>'+st.desc+'</p>'+requirementsHTML(p,st.requirements)+'</details>').join('')+(!next.length?'<div class="notice">현재 포지션의 모든 플레이스타일을 익혔습니다.</div>':'')+btn('전체 플레이스타일 보기 →','show-styles','','outline full')+btn('아키타입별 + 강화 보기 →','show-plus','','text-button full')+'</section>';
}
function styleIcon(id){return '<span class="style-emblem"><img class="reference-style-icon" src="'+FootballStyleIcons[id]+'" alt="" width="36" height="36" decoding="async" aria-hidden="true"></span>'}
function stylesPanel(){
 const p=game.player,all=Object.values(E.STYLES),allowed=E.availableStyles(p).map(s=>s.id),cats=[...new Set(all.map(s=>s.category))];
 return '<section class="card"><div class="row"><h3>자동 적용 플레이스타일</h3>'+badge(p.unlocked.length+'개 획득','teal')+'</div><div class="chips">'+(p.unlocked.length?p.unlocked.map(id=>badge(E.STYLES[id].name+(E.plus(p,id)?'+':''),E.plus(p,id)?'gold':'teal')).join(''):'<p class="help">아직 획득한 특성이 없습니다. 훈련과 출전으로 조건을 채워 보세요.</p>')+'</div>'+(p.weakFoot>=85?'<div class="innate-trait">양발잡이 '+badge(p.talentId==='ambidextrous'?'타고난 특성':'훈련으로 습득','teal')+'</div>':'')+'<p class="help">기본 특성은 장착할 필요 없이 모두 적용됩니다. 한 번 익힌 특성은 능력치가 내려가도 유지됩니다. 아이콘을 누르면 세부 조건을 확인할 수 있습니다.</p>'+btn('아키타입별 플레이스타일+ 강화 →','show-plus','','outline full')+'</section><div class="filter-chips">'+['전체',...cats].map(c=>btn(c,'style-filter','data-value="'+c+'"','filter '+(styleCategory===c?'active':''))).join('')+'</div><div class="style-gallery">'+cats.filter(c=>styleCategory==='전체'||c===styleCategory).map(category=>'<section class="style-category"><h3>'+category+'</h3><div class="style-icon-grid">'+all.filter(s=>s.category===category).map(s=>{const eligible=allowed.includes(s.id),on=eligible&&p.unlocked.includes(s.id),boost=on&&E.plus(p,s.id),state=boost?'+ 강화 적용':on?'자동 적용':eligible?'성장 필요':'포지션 제한';return btn(styleIcon(s.id)+'<b>'+s.name+(boost?'+':'')+'</b><small>'+state+'</small>','style-info','data-value="'+s.id+'" aria-label="'+s.name+' · '+state+'"','style-tile '+(on?'equipped':'locked')+(boost?' plus':''))}).join('')+'</div></section>').join('')+'</div><p class="help">참고 빌더의 요구 능력을 이 게임의 22개 능력치에 대응시켰습니다. +의 강화 칸과 경기 효과는 이 게임의 규칙입니다. <a href="https://fc27builderbuilder.pages.dev/" target="_blank" rel="noopener noreferrer">아이콘 출처 · FC27 클럽 빌더</a></p>';
}
function styleInfo(id){
 const p=game.player,s=E.STYLES[id];if(!s)return;
 const allowed=E.availableStyles(p).some(a=>a.id===id),on=p.unlocked.includes(id),boost=E.plus(p,id),effect={goal:'개인 득점 비중',assist:'개인 도움 비중',attack:'팀 공격 기대값',defend:'실점 억제 계수',fitness:'체력 유지 계수'}[s.effect];
 dialog(s.name+(boost?'+':''),'<div class="style-detail-icon">'+styleIcon(id)+'</div><p>'+s.desc+'</p><div class="effect">'+effect+' 기본 +'+Math.round(s.value*100)+'%'+(boost?' · + 강화 추가 '+Math.round(s.value*.7*100)+'%':'')+'</div><h3>해금 조건 · 모두 충족</h3>'+requirementsHTML(p,s.requirements)+'<div class="notice">'+(!allowed?'현재 포지션에서는 획득할 수 없는 특성입니다.':on?'획득 완료 · 경기에 자동 적용됩니다. 익힌 특성은 현재 능력치와 관계없이 유지됩니다.':'별도 레벨 제한 없이 요구 능력치를 모두 달성하면 자동 획득합니다.')+'</div><p class="help">기본 특성의 동일 계열 효과는 합산 상한이 있습니다. + 강화는 상한에 추가로 반영됩니다.</p>'+(!boost&&E.plusOptions(p).some(o=>o.style===id)?'<p class="help">현재 아키타입에 이 특성의 + 강화 경로가 있습니다. 플레이스타일+ 카드에서 조건을 확인하세요.</p>':''));
}
function talentGuide(){dialog('타고난 재능 10종','<div class="talent-catalog">'+Object.values(E.TALENTS).map(t=>'<article><h3>'+t.name+'</h3><p>'+t.desc+'</p></article>').join('')+'</div><p>이 중 서로 다른 세 가지 재능이 후보로 등장합니다. 재능은 선수 생성 후에도 유지됩니다.</p>')}

function focusPicker(){
 const p=deck[selected],sections=E.POSITION_ATTRIBUTES[p.pos];
 return'<section class="card focus-picker"><div class="row"><h3>집중 육성 능력</h3>'+badge(draft.focus.length+' / 2 선택')+'</div><p class="help">'+E.POS[p.pos].name+'의 세부 능력치 중 최대 2개를 고릅니다. 선택한 능력은 훈련 성장량이 25% 높아집니다.</p>'+sections.map(section=>{
  const buttons='<div class="grid two">'+section.keys.map(id=>btn('<span>'+E.attributeName(id)+'</span><b>'+Math.round(p.details[id])+'</b>','focus','data-value="'+id+'" aria-pressed="'+draft.focus.includes(id)+'"','choice focus-choice '+(draft.focus.includes(id)?'selected':''))).join('')+'</div>';
  return section.collapsed?'<details class="focus-section disclosure" data-group="focus-other-'+p.pos+'"><summary>기타 능력치 <span>5개</span></summary>'+buttons+'</details>':'<section class="focus-section"><h4>'+section.name+'</h4>'+buttons+'</section>';
 }).join('')+'<p class="focus-selection" aria-live="polite">'+(draft.focus.length?'선택 · '+draft.focus.map(E.attributeName).join(' / '):'집중 육성을 선택하지 않아도 시작할 수 있습니다.')+'</p><p class="help">나이에 따른 성장 제한은 동일합니다. 30세부터 피지컬은 유지 훈련으로 하락 속도를 늦춥니다.</p></section>';
}
function growth(){
 return'<main><header class="simple-header">'+btn('← 후보 다시 선택','talents','','outline')+'<b>성장 방향</b></header><div class="content">'+title('CHAPTER 03','어떤 선수로 성장할까요?','아키타입은 성장 강점, 플레이스타일은 경기에서 쓰는 특성입니다.')+'<h3>'+E.POS[draft.pos].name+' 아키타입 선택</h3><div class="stack">'+E.eligibleArch(draft.pos).map(([id,a])=>btn('<div class="row"><b>'+a.name+'</b>'+badge(a.plain)+'</div><p>'+a.desc+'</p><small>주요 능력 · '+a.keys.map(attrName).join(' / ')+'</small>','archetype','data-value="'+id+'" aria-pressed="'+(draft.archetypeId===id)+'"','option '+(draft.archetypeId===id?'selected':''))).join('')+'</div><section class="card"><h3>전술 성향</h3><div class="grid two">'+Object.entries(E.TACTICS).map(([id,t])=>btn('<b>'+t.name+'</b><small>'+t.desc+'</small>','tactic','data-value="'+id+'" aria-pressed="'+(draft.tactic===id)+'"','choice '+(draft.tactic===id?'selected':''))).join('')+'</div></section>'+focusPicker()+btn('첫 소속 배정 · 시작 →','begin')+'</div></main>';
}
function trainPanel(){
 const fixed=game.period.trained,p=game.player,phase=E.agePhase(game.age),plans=E.trainingOptions(game),selectedPlan=plans.find(t=>t.id===game.training)||plans[0],focus=p.focus.map(E.attributeName);
 return '<section class="card training-card"><div class="row"><h3>소속팀 훈련</h3>'+badge(fixed?'이번 반기 진행 중':'반기마다 선택')+'</div><details class="age-growth disclosure" data-group="age-growth"><summary>'+game.age+'세 · '+phase.name+'</summary><p>'+phase.desc+'</p><ol class="age-steps">'+[['young','~21세','피지컬'],['prime','22~29세','기술'],['veteran','30세~','유지 · 판단']].map(([id,age,name])=>'<li class="'+(phase.id===id?'active':'')+'"><span>'+age+'</span><b>'+name+'</b></li>').join('')+'</ol></details><div class="grid two training-options">'+plans.map(plan=>btn('<b>'+plan.name+'</b>','training','data-value="'+plan.id+'" aria-pressed="'+(selectedPlan.id===plan.id)+'" '+(fixed||plan.id==='weak'&&p.weakFoot>=100?'disabled':''),'choice training-option '+(selectedPlan.id===plan.id?'selected':''))).join('')+'</div><div class="training-target"><b>'+selectedPlan.name+'</b><p>'+(selectedPlan.id==='weak'?'약발 숙련도를 높입니다. 다른 능력의 성장량은 35%로 줄어듭니다.':selectedPlan.id==='balanced'?'포지션의 17개 능력을 나이별 성장 특성에 맞춰 훈련합니다.':selectedPlan.id==='physical'&&game.age>=30?'성장 없이 신체 능력의 하락 속도를 늦춥니다.':selectedPlan.keys.map(E.attributeName).join(' · '))+'</p>'+(focus.length?'<p class="focus-target">집중 육성 · '+focus.join(' / ')+'</p>':'')+'</div>'+(selectedPlan.id==='weak'?'<div class="weak-line"><span>약발 숙련도 <b>'+p.weakFoot+'/100</b></span>'+badge(p.weakFoot>=85?'양발 활용 가능':foot(p)+' 주발')+'</div>'+bar(p.weakFoot,'teal')+'<p class="help">85에 도달하면 양발을 활용할 수 있습니다.</p>':'')+'<h4>훈련 강도</h4><div class="grid three">'+Object.entries(E.INTENSITIES).map(([id,intensity])=>btn('<b>'+intensity.name+'</b><small>'+({light:'회복 우선',normal:'성장과 회복',hard:'성장 · 부상 위험 ↑'}[id])+'</small>','intensity','data-value="'+id+'" aria-pressed="'+(game.intensity===id)+'" '+(fixed?'disabled':''),'choice '+(game.intensity===id?'selected':''))).join('')+'</div><p class="help">'+(fixed?'이번 반기에는 계획이 고정됩니다.':'강도를 높이면 성장량과 체력 소모·부상 위험이 함께 늘어납니다.')+'</p></section>';
}
function trainingReport(s){
 const t=s.trainingReview;if(!t)return '';
 const signed=n=>(n>0?'+':'')+Number(n||0).toFixed(1),rows=[['훈련',t.summary],['클럽 경기',t.experience],['A매치',t.national],['노화',t.aging]].filter(([,data])=>data);
 return '<div class="training-result"><b>'+esc(t.plan)+' · '+esc(t.intensity)+'</b><p>'+esc(t.phase)+'</p><div class="growth-table-wrap"><table class="growth-table"><thead><tr><th>변화 원인</th><th>피지컬</th><th>기술</th><th>판단</th></tr></thead><tbody>'+rows.map(([name,data])=>'<tr><th>'+name+'</th>'+['physical','technique','mental'].map(id=>'<td class="'+(data[id]<0?'negative':'')+'">'+signed(data[id])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="help">세부 능력치 변화량의 합계입니다. 종합 능력 상승폭과는 다릅니다.</p>'+(t.injuredDays?'<p class="injury-note">부상으로 훈련 제한 · '+t.injuredDays+'일</p>':'')+(t.weakGain?'<p>약발 숙련도 +'+t.weakGain+'</p>':'')+'</div>';
}
function clubStrip(){return'<div class="club-strip"><div><b>'+esc(E.teamName(game))+'</b><span>'+E.LEAGUES[game.country].name+' · '+E.dateText(game.clock)+'</span></div>'+badge(game.stage==='pro'?'프로':game.stage==='middle'?'U15':'U18')+'</div>'}
function condition(){return'<div class="condition">'+metric('현재 경기 능력',E.effective(game))+metric('컨디션',Math.round(game.form))+metric('경기 체력',Math.round(game.fitness))+'</div>'}

function progress(){let span=game.target-game.period.start,percent=(game.clock-game.period.start)/span*100;return'<div class="timeline"><div class="row"><span>'+E.dateText(game.period.start)+'</span><b>'+windowLabel(game.target)+'</b></div>'+bar(percent)+'<p>'+E.date(game.target).year+'년 '+E.date(game.target).month+'월까지 진행 · 국가대표 발탁 시 중간 정지</p></div>'}
function statMetrics(s){return'<div class="metrics three">'+metric('출전',s.apps)+metric(game.player.pos==='GK'?'선방':'골',game.player.pos==='GK'?s.saves:s.goals)+metric(game.player.pos==='GK'?'무실점':'도움',game.player.pos==='GK'?s.clean:s.assists)+'</div><div class="metrics three secondary">'+metric('출전 시간',s.minutes+'분')+metric('평균 평점',rating(s))+metric('선발',s.starts)+'</div>'}
function originPanel(){
 const o=game.startOrigin;if(game.history.length||!o||o.kind==='legacy')return '';
 return '<section class="card origin-card"><span class="eyebrow">'+(o.rare?'1%의 기회 · 해외 유스 발탁':'첫 소속 추첨 완료')+'</span><h3>'+esc(o.name)+'</h3><p>'+esc(o.rare?'15세, 해외 아카데미에서 새로운 축구 인생을 시작합니다.':o.basis||'기존 커리어의 시작 학교를 이어갑니다.')+'</p><small>소속은 저장됩니다. 다시 열어도 바뀌지 않습니다.</small></section>';
}
function cupBracket(c){
 const name=id=>c.teams.find(t=>t.id===id)?.name||id,my=c.playerClub||game.clubId;
 return '<details class="disclosure cup-bracket" data-group="cup-'+c.id+'"><summary>대진표 '+(c.complete?'· 최종 결과':'· 추첨 완료')+'</summary>'+c.rounds.map(r=>'<section><h4>'+r.name+'</h4>'+r.matches.map(f=>'<article class="bracket-match '+([f.h,f.a].includes(my)?'own-fixture':'')+'"><div class="'+(f.winner===f.h?'winner':'')+'"><span>'+esc(name(f.h))+'</span><b>'+(f.done?f.x:'—')+'</b></div><div class="'+(f.winner===f.a?'winner':'')+'"><span>'+esc(name(f.a))+'</span><b>'+(f.done?f.y:'—')+'</b></div>'+(f.penH!==undefined?'<small>승부차기 '+f.penH+' : '+f.penA+'</small>':'')+'</article>').join('')+'</section>').join('')+'</details>';
}
function cupCalendar(){
 if(!E.usesYouthCups(game))return '';
 const s=E.youthSeason(game);
 return '<section class="card cup-calendar"><div class="row"><h3>'+s.year+' 유소년 토너먼트</h3>'+badge(s.teams.length+'팀')+'</div><p class="help">패하면 탈락합니다. 정규시간 동점은 승부차기로 결정합니다.</p>'+s.cups.map(c=>'<article class="cup-entry"><div class="row"><div><small>'+c.month+'월 '+c.day+'일 시작</small><b>'+c.name+'</b></div>'+badge(c.playerResult|| (c.complete?'종료':'출전 예정'),c.playerResult==='우승'?'gold':'')+'</div>'+cupBracket(c)+'</article>').join('')+'<p class="help">'+(game.country==='KR'?'실제 대회명을 참고한 축약 토너먼트입니다. 참가 팀과 날짜는 게임에 맞게 구성했습니다.':'실제 구단 유스가 참가하는 게임 속 초청컵입니다. 대회명과 일정은 가상입니다.')+'</p></section>';
}
function cupResults(cups){
 if(!cups?.length)return '';
 return '<section class="card"><h3>토너먼트 성적</h3>'+cups.map(c=>'<article class="cup-entry"><div class="row"><div><small>'+c.year+' · '+esc(c.club)+'</small><b>'+c.name+'</b></div>'+badge(c.result,c.result==='우승'?'gold':'')+'</div>'+cupBracket(c)+'</article>').join('')+'</section>';
}
function matchList(matches){
 return '<details class="card disclosure"><summary>경기별 기록 <span>'+matches.length+'경기</span></summary><div class="match-list">'+(matches.length?[...matches].reverse().map(m=>'<article><div class="row"><span>'+(m.competition?E.date(m.date).year+'년 '+m.cupMonth+'월 '+m.cupDay+'일':E.dateText(m.date))+'</span>'+badge(m.status,m.injured?'injury':'')+'</div>'+(m.competition?'<p class="competition-label">'+esc(m.competition)+' · '+m.round+' · '+(m.won?(m.round==='결승'?'우승':'진출'):'탈락')+'</p>':'')+'<div class="score-row"><b>'+esc(m.opponent)+'</b><strong>'+m.own+' : '+m.opp+'</strong></div>'+(m.shootout?'<p class="shootout-score">승부차기 '+m.shootout.own+' : '+m.shootout.opp+'</p>':'')+'<p>'+m.minutes+'분 · '+(game.player.pos==='GK'?'선방 '+m.saves+' · 실점 '+(m.conceded??'—'):m.goals+'골 · '+m.assists+'도움')+(m.minutes?' · 평점 '+m.rating:'')+'</p>'+(m.modelVersion>=3&&m.minutes?'<div class="match-numbers">'+(game.player.pos==='GK'?'<span>상대 유효 슈팅 '+m.facedOnTarget+'</span>':'<span>슈팅 '+m.shots+' · 유효 '+m.onTarget+'</span>')+'<span>패스 '+m.completed+' / '+m.passes+'</span>'+(['CB','FB','MF'].includes(game.player.pos)?'<span>태클 '+m.tackles+' · 가로채기 '+m.interceptions+'</span>':'')+'</div>':'')+(m.injury?'<p class="injury-note">'+esc(m.injury.name)+' · '+m.injury.days+'일 회복</p>':'')+'</article>').join(''):'<p class="help">첫 경기를 기다리고 있습니다.</p>')+'</div></details>';
}
function report(r){
 if(!r)return '<div class="notice">아직 기록된 반기가 없습니다.</div>';
 const modern=r.matches.filter(m=>m.modelVersion>=3&&m.minutes),sum=id=>modern.reduce((n,m)=>n+(m[id]||0),0),percent=(n,d)=>d?(n/d*100).toFixed(1)+'%':'—';
 const details=game.player.pos==='GK'?[['선방 / 상대 유효 슈팅',sum('saves')+' / '+sum('facedOnTarget')],['선방률',percent(sum('saves'),sum('facedOnTarget'))],['출전 중 실점',sum('conceded')]]:[['슈팅 / 유효 슈팅',r.shots+' / '+r.onTarget],['득점 전환율',percent(r.goals,r.shots)],['드리블 성공 / 시도',sum('dribbles')+' / '+sum('dribbleAttempts')],['태클 성공 / 시도',sum('tackles')+' / '+sum('tackleAttempts')],['가로채기',sum('interceptions')]];
 details.push(['패스 성공 / 시도',r.completed+' / '+r.passes],['패스 성공률',percent(r.completed,r.passes)],['무실점 출전',r.clean],['부상 결장',r.matches.filter(m=>m.injured&&!m.minutes).length+'경기']);
 return '<section class="card review-card">'+title('반기 마무리','반기 기록',E.dateText(r.start)+' → '+E.dateText(r.end))+statMetrics(r)+'<div class="review">종합 능력 '+r.startOvr+' → '+(r.endOvr??E.overall(game.player))+' <b>'+(r.growth>=0?'+':'')+r.growth+'</b></div><details class="review-fold disclosure" name="period-review" data-group="review-training"><summary>능력 변화 · 주요 소식</summary>'+trainingReport(r)+((r.events||[]).length?'<ul class="event-list">'+r.events.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':'')+'</details>'+(r.cups?.length?'<details class="review-fold disclosure" name="period-review" data-group="review-cups"><summary>토너먼트 성적 <span>'+r.cups.length+'개 대회</span></summary>'+cupResults(r.cups)+'</details>':'')+matchList(r.matches).replace('class="card disclosure"','class="review-fold disclosure" name="period-review" data-group="review-matches"')+'<details class="review-fold disclosure" name="period-review" data-group="review-stats"><summary>상세 기록 · 경기 특성</summary><div class="detail-table">'+details.map(([k,v])=>'<div><span>'+k+'</span><b>'+v+'</b></div>').join('')+'</div>'+(!modern.length?'<p class="help">이전 기록에는 새로 추가된 세부 항목이 없습니다.</p>':'')+'<div class="chips">'+Object.entries(r.activations||{}).filter(([id])=>E.STYLES[id]).map(([id,n])=>badge(E.STYLES[id].name+' · '+n+'경기','teal')).join('')+'</div></details></section>';
}
function offersScreen(){const grad=game.stage==='middle'&&E.date(game.clock).month===1;return title(grad?'NEXT CHAPTER':'TRANSFER WINDOW',grad?'중학교 졸업 · 다음 무대':windowLabel(game.clock),grad?'다음 소속을 선택하세요.':'다음 반기를 함께할 팀을 선택하세요.')+'<section class="card offers-card"><h3>'+(grad?'고교 / 해외 유스 제안':'계약 제안')+'</h3><div class="stack">'+game.offers.map(o=>'<article class="offer '+(o.rare?'rare':'')+'"><div class="row">'+badge(o.kind==='stay'?'소속팀 계속':o.kind==='academy'?(o.schoolTeam?'고교 진학':'유스 입단'):'프로 계약')+(o.country?badge(E.LEAGUES[o.country].name):'')+'</div><h3>'+esc(o.name)+'</h3>'+(o.rare?'<p class="rare-note">희귀한 기회 · 해외 유스 영입 제안</p>':'')+(o.kind==='pro'||game.stage==='pro'?'<p>연봉 '+money(o.wage||game.wage)+' · 계약 '+(o.months||game.contract)+'개월</p><small>'+esc(o.role||'현재 팀에서 커리어를 이어갑니다.')+'</small>':'<p>'+(o.kind==='academy'?(o.schoolTeam?'고교 축구부에서 성장하며 프로 구단의 제안을 기다립니다.':'구단 산하 유스에서 성장하고 프로 입단에 도전합니다.'):'중3 시즌을 마치면 진학 제안이 도착합니다.')+'</p>')+btn(o.kind==='stay'?'계속하기 →':'이 제안 선택 →','offer','data-value="'+esc(o.id)+'"','primary')+'</article>').join('')+'</div>'+(grad?'<p class="help">해외 유스 제안 확률은 졸업 시 1%입니다. 이번 게임에서 정한 확률이며, 제안은 저장되어 다시 열어도 바뀌지 않습니다.</p>':'')+'</section>'}

function market(){
 const grad=game.stage==='middle'&&E.date(game.clock).month===1,choosing=game.marketStep==='offers';
 const steps='<ol class="flow-steps" aria-label="반기 마무리 순서"><li class="'+(!choosing?'active':'done')+'">1 · 결과 확인</li><li class="'+(choosing?'active':'')+'">2 · '+(grad?'진학 선택':'제안 선택')+'</li></ol>';
 return steps+(choosing?btn('← 이전 결과 보기','market-back','','text-button')+offersScreen():report(game.history.at(-1))+btn(grad?'다음 · 중학교 졸업과 진학 제안 →':'다음 · '+windowLabel(game.clock)+' 제안 확인 →','market-next'));
}

function international(){const c=game.camp;return'<section class="national-card"><span class="eyebrow">KOREA REPUBLIC</span><h2>국가대표 소집</h2><p>'+esc(game.player.name)+', 태극마크를 달다.</p><div class="flag">🇰🇷</div><b>'+E.dateText(c.date)+' · A매치 '+c.matches.length+'/2</b><p>소속팀 일정이 잠시 멈췄습니다.<br>대표팀 경기를 마친 뒤 같은 지점에서 복귀합니다.</p></section><section class="card"><h3>이번 대표팀 일정</h3><div class="stack">'+c.opponents.map((o,i)=>'<div class="national-match"><span>대한민국 <b>vs '+o+'</b></span><strong>'+(c.matches[i]?c.matches[i].own+' : '+c.matches[i].opp:'경기 대기')+'</strong>'+(c.matches[i]?'<p>'+c.matches[i].minutes+'분 · '+c.matches[i].goals+'골 · '+c.matches[i].assists+'도움</p>':'')+'</div>').join('')+'</div>'+btn(c.complete?'소속팀으로 복귀 →':'A매치 '+(c.matches.length+1)+'경기 진행 →',c.complete?'return':'international')+'</section><div class="notice">A매치 기록은 클럽 기록과 별도로 쌓입니다. 유스 대표팀, 실제 예선 조 편성과 본선 대회는 아직 포함하지 않은 A매치 모드입니다.</div>'}
function season(){
 if(game.phase==='international')return international();if(game.phase==='market')return market();
 if(game.retired)return title('END OF CAREER','당신의 축구 인생',esc(game.player.name)+'의 마지막 휘슬이 울렸습니다.')+career()+btn('새로운 인생 시작','new');
 const panes=[['training','훈련'],['schedule','일정'],['traits','특성']],subnav='<nav class="season-subtabs" aria-label="시즌 화면 선택">'+panes.map(([id,label])=>btn(label,'season-view','data-value="'+id+'" aria-pressed="'+(seasonView===id)+'"','filter '+(seasonView===id?'active':''))).join('')+'</nav>';
 const origin=game.history.length===0&&game.startOrigin?.kind!=='legacy'?'<div class="origin-compact">'+badge(game.startOrigin?.rare?'1%의 기회 · 해외 유스 발탁':'첫 소속 추첨 완료','teal')+'<span>'+esc(game.startOrigin?.name||E.teamName(game))+'</span></div>':'';
 let content;
 if(seasonView==='schedule')content=(E.usesYouthCups(game)?cupCalendar():clubSchedule())+(game.period.matches.length?matchList(game.period.matches):'');
 else if(seasonView==='traits')content=trainingStyles();
 else content=trainPanel()+btn(windowLabel(game.target)+'까지 '+(game.period.trained?'계속 진행':'진행')+' →','advance');
 const injury=E.injuryAt(game);return clubStrip()+(injury?'<div class="injury-banner"><b>'+esc(injury.name)+'</b><span>회복까지 '+E.injuryDays(game)+'일 · 출전 불가</span></div>':'')+origin+'<div class="condition-strip"><span>컨디션 <b>'+Math.round(game.form)+'</b></span><span>체력 <b>'+Math.round(game.fitness)+'</b></span><span>경기 능력 <b>'+E.effective(game)+'</b></span></div>'+subnav+'<div class="season-pane" data-season-pane="'+seasonView+'">'+content+'</div>';
}
function clubSchedule(){
 const world=E.seasonWorld(game),upcoming=world.fixtures.filter(f=>!f.done&&f.t>=game.clock&&f.t<game.target&&(f.h===game.clubId||f.a===game.clubId));
 return '<section class="card"><h3>다음 이적시장까지</h3>'+progress()+'<div class="fixture-preview">'+(upcoming.length?upcoming.map(f=>'<article><span>'+E.dateText(f.t)+'</span><b>'+esc(world.teams.find(c=>c.id===(f.h===game.clubId?f.a:f.h))?.name||'상대팀')+'</b><small>'+(f.h===game.clubId?'홈':'원정')+'</small></article>').join(''):'<p class="help">이 기간의 예정 경기가 없습니다.</p>')+'</div></section>';
}
function player(){const p=game.player;return title('PLAYER','선수 성장','능력치, 성장 유형, 경기 특성을 나누어 볼 수 있습니다.')+'<div class="subtabs">'+[['attributes','능력치'],['archetype','아키타입'],['styles','플레이스타일']].map(([id,t])=>btn(t,'player-tab','data-value="'+id+'"','filter '+(playerTab===id?'active':''))).join('')+'</div>'+(playerTab==='attributes'?attributes():playerTab==='archetype'?archetypePanel():stylesPanel())+'<details class="card disclosure profile-fold" data-group="player-profile"><summary>선수 프로필</summary><div class="detail-table">'+[['이름 / 등번호',p.name+' / '+p.number],['나이 / 포지션',game.age+'세 / '+E.POS[p.pos].name],['전술 성향',E.TACTICS[p.tactic].name],['집중 육성',p.focus.map(E.attributeName).join(' / ')||'선택 없음'],['타고난 재능',E.talent(p).name],['주발',foot(p)+(p.weakFoot>=85?' · 양발 활용':'')],['소속팀',E.teamName(game)],['연봉',money(game.wage)],['구단 신뢰',Math.round(game.trust)+'/100'],['인지도',Math.round(game.reputation)],['커리어 ID',game.id]].map(([k,v])=>'<div><span>'+k+'</span><b>'+esc(v)+'</b></div>').join('')+'</div></details>'}
function career(){const s=E.totals(game),nt=game.national.reduce((a,r)=>({apps:a.apps+1,goals:a.goals+r.goals,assists:a.assists+r.assists,saves:a.saves+r.saves,clean:a.clean+r.clean}),{apps:0,goals:0,assists:0,saves:0,clean:0});const seasonMap={};for(const r of [...game.history,...(['ready','international'].includes(game.phase)?[game.period]:[])])for(const m of r.matches){let key=m.league+'|'+m.country+'|'+m.club;let a=seasonMap[key]||(seasonMap[key]={season:m.league,country:m.country,club:m.club,...E.blankStats()});a.apps+=m.minutes>0?1:0;a.minutes+=m.minutes;a.goals+=m.goals;a.assists+=m.assists;a.saves+=m.saves;a.clean+=m.clean;a.ratingSum+=m.rating}return'<section class="card">'+title('CAREER','나의 축구 기록','중학교 · 유스 · 프로의 클럽 기록입니다.')+statMetrics(s)+'<div class="review">누적 수입 <b>'+money(game.income)+'</b></div></section><section class="card"><h3>🇰🇷 대한민국 A매치</h3><div class="metrics three">'+metric('출전',nt.apps)+metric(game.player.pos==='GK'?'선방':'골',game.player.pos==='GK'?nt.saves:nt.goals)+metric(game.player.pos==='GK'?'무실점':'도움',game.player.pos==='GK'?nt.clean:nt.assists)+'</div><p class="help">국가대표 기록은 위 클럽 기록에 합산하지 않습니다.</p>'+(game.national.length?'<details class="disclosure"><summary>A매치 상세 기록</summary><div class="match-list">'+[...game.national].reverse().map(r=>'<article><div class="row"><b>'+r.opponent+'</b><strong>'+r.own+' : '+r.opp+'</strong></div><p>'+E.dateText(r.date)+' · '+r.goals+'골 '+r.assists+'도움</p></article>').join('')+'</div></details>':'')+'</section><section class="card"><h3>시즌별 · 소속팀별 기록</h3><p class="help">유소년 토너먼트는 연도별, 프로는 유럽 8월~다음 해 5월·한국 3~11월로 묶습니다. 겨울 이적시장에서도 시즌 기록은 이어집니다.</p><div class="stack">'+(Object.values(seasonMap).reverse().map(r=>'<article class="season-row"><span>'+r.season+' · '+E.LEAGUES[r.country].name+'</span><b>'+esc(r.club)+'</b><p>'+r.apps+'경기 · '+r.goals+'골 · '+r.assists+'도움 · 평점 '+rating(r)+'</p>'+(game.player.pos==='GK'?'<p>선방 '+r.saves+' · 무실점 '+r.clean+'</p>':'')+'</article>').join('')||'<p class="help">첫 경기를 기다리고 있습니다.</p>')+'</div></section><section class="card"><h3>발자취와 트로피</h3><ul class="event-list"><li>'+game.startYear+'년 3월 · '+esc(game.startOrigin?.name||E.school(game.middleSchoolId)?.name||'중학교')+(game.startOrigin?.rare?' · 해외 유스 특별 발탁':' · 중3 시작')+'</li>'+game.journey.map(j=>'<li>'+E.dateText(j.date)+' · '+esc(j.name)+(j.rare?' · 해외 유스 특별 제안':'')+'</li>').join('')+game.trophies.map(t=>'<li>🏆 '+t.year+' · '+esc(t.club)+' · '+t.name+'</li>').join('')+'</ul></section>'+cupResults([...game.history,...(['ready','international'].includes(game.phase)?[game.period]:[])].flatMap(r=>r.cups||[]).reverse())+(game.age>=30&&!game.retired&&game.phase!=='international'?btn('은퇴하고 기록 남기기','retire','','outline full'):'')}
function league(){const w=E.seasonWorld(game,leagueCountry,'pro'),table=E.sortTable(w),champ=game.champions.filter(c=>c.country===leagueCountry);return title('LEAGUE','리그와 우승 연혁','실제 구단으로 구성된 게임 속 리그입니다.')+'<label class="select-label">국가<select id="league-country">'+Object.entries(E.LEAGUES).map(([id,c])=>'<option value="'+id+'" '+(leagueCountry===id?'selected':'')+'>'+c.flag+' '+c.name+' · '+E.leagueName(game,id)+'</option>').join('')+'</select></label><section class="card"><div class="row"><h3>'+E.leagueName(game,leagueCountry)+'</h3>'+badge(E.leagueLabel(w))+'</div><p class="help">'+(w.complete?'시즌 종료':w.table.some(t=>t.p)?'시즌 진행 중':'개막 전')+' · 표는 좌우로 움직여 볼 수 있습니다.</p><div class="table-scroll"><table><thead><tr><th>순위 / 구단</th><th>경기</th><th>승</th><th>무</th><th>패</th><th>득실</th><th>승점</th></tr></thead><tbody>'+table.map((c,i)=>'<tr class="'+(game.stage==='pro'&&c.id===game.clubId?'my-team':'')+'"><th>'+(i+1)+'. '+esc(c.name)+'</th><td>'+c.p+'</td><td>'+c.w+'</td><td>'+c.d+'</td><td>'+c.l+'</td><td>'+(c.gf-c.ga)+'</td><td><b>'+c.pts+'</b></td></tr>').join('')+'</tbody></table></div></section><section class="card"><h3>🏆 우승 연혁</h3><div class="stack">'+(champ.length?[...champ].reverse().map(c=>'<article class="season-row"><span>'+c.season+'</span><b>우승 · '+esc(c.winner)+'</b><p>준우승 · '+esc(c.runner)+'</p></article>').join(''):'<p class="help">첫 시즌이 끝나면 결과가 기록됩니다.</p>')+'</div></section><div class="notice">'+(game.era==='2000'?'구단은 한국 2000년, 유럽 2000/01 시즌의 실제 104개 팀을 바탕으로 고정합니다. 한국은 10팀·27경기, 유럽은 홈·원정 리그입니다.':'기존 커리어의 2026 / 2026–27 구단 구성과 대회 방식을 유지합니다.')+' 경기 결과와 우승은 새로 계산됩니다. 승강제·대륙대항전·당시 한국의 플레이오프 및 무승부 승부차기는 생략했습니다.</div>'}
function archivesScreen(){
 const records=[...(game?[{g:game,source:'active',index:0}]:[]),...archives.map((g,index)=>({g,source:'archives',index})),...legacy.map((g,index)=>({g,source:'legacy',index}))];
 return '<main><div class="content">'+title('MEMORIES','보관한 축구 인생','진행 중인 선수와 보관한 커리어입니다.')+'<div class="archive-list">'+records.map(({g,source,index})=>{const p=g.player||{},h=g.history||[],total=g.version===2?E.totals(g):{apps:h.reduce((n,r)=>n+(r.apps||0),0),goals:h.reduce((n,r)=>n+(r.goals||0),0)},apps=total.apps,goals=total.goals,current=source==='active';return '<article class="card archive-card" data-record-source="'+source+'" data-record-index="'+index+'"><div class="row"><h3>'+esc(p.name||'이전 선수')+'</h3>'+badge(current?(g.retired?'은퇴한 인생':'진행 중'):g.version===2?'완료 / 보관':'이전 버전',current?'teal':'')+'</div><p>'+esc(g.age||'—')+'세 · '+apps+'경기 · '+goals+'골</p><div class="archive-actions">'+(current?btn(g.retired?'기록 보기':'이어서 하기','hub','','outline'):'<span class="help">'+(g.version===2?'보관된 커리어':'이전 버전 기록')+'</span>')+btn('이 인생 삭제','delete-career','data-source="'+source+'" data-index="'+index+'" aria-label="'+esc(p.name||'이전 선수')+'의 축구 인생 삭제"','danger-text')+'</div></article>'}).join('')+'</div>'+(!records.length?'<div class="notice">저장된 축구 인생이 없습니다.</div>'+btn('새로운 인생 시작','new'):'')+btn('홈으로','home','','outline full')+'</div></main>';
}
function requestCareerDeletion(source,index){
 const list=source==='archives'?archives:source==='legacy'?legacy:null,target=source==='active'?game:list?.[index];
 if(!target||!['active','archives','legacy'].includes(source))return;
 pendingDeletion={source,index,target};
 dialog('이 축구 인생을 삭제할까요?','<p><b>'+esc(target.player?.name||'이전 선수')+'</b> · '+esc(target.age||'—')+'세</p><p>선택한 인생의 진행 상황과 기록을 삭제합니다. 다른 축구 인생은 유지됩니다.</p><p class="help">삭제한 기록은 게임 안에서 복구할 수 없습니다.</p>','confirm-delete-career','삭제하기');
}
function confirmCareerDeletion(){
 const request=pendingDeletion;if(!request)return false;
 const {source,index,target}=request,list=source==='archives'?archives:source==='legacy'?legacy:null;
 if((source==='active'?game:list?.[index])!==target){pendingDeletion=null;return false}
 if(source==='active')game=null;else list.splice(index,1);
 if(!save()){if(source==='active')game=target;else list.splice(index,0,target);toast('저장 공간에 반영하지 못해 삭제를 취소했습니다.');return false}
 pendingDeletion=null;document.getElementById('dialog').close();screen='archives';tab='season';seasonView='training';toast('선택한 축구 인생을 삭제했습니다.');return true;
}
function hub(){if(!game)return'<main><div class="content">'+title('NEW STORY','아직 시작하지 않은 이야기','새 선수를 만들어 축구 인생을 시작하세요.')+btn('선수 생성','new')+'</div></main>';return header()+'<main class="content career-content">'+(!saveOK?'<div class="notice error">이 브라우저에서 자동 저장을 사용할 수 없습니다. 아래 기록 백업 버튼으로 저장해 주세요.</div>':'')+(tab==='season'?season():tab==='career'?career():tab==='player'?player():league())+'<div class="save-status">'+(saveOK?'● 진행 상황 자동 저장':'저장 공간을 확인해 주세요')+'<button data-action="export" class="text-button">기록 백업</button></div></main>'}
function render(keepScroll=false){let y=window.scrollY,opened=[...document.querySelectorAll('details[data-group][open]')].map(e=>e.dataset.group);if(app.dataset)app.dataset.screen=screen;document.documentElement?.classList.toggle('reduce-motion',reducedMotion);app.innerHTML=(screen==='home'?home():screen==='create'?creation():screen==='talents'?candidateScreen():screen==='growth'?growth():screen==='archives'?archivesScreen():screen==='settings'?settings():hub())+nav();document.querySelectorAll('button:not([type])').forEach(b=>b.type='button');if(keepScroll){if(opened.length)document.querySelectorAll('details[data-group]').forEach(e=>e.open=opened.includes(e.dataset.group));window.scrollTo(0,y)}else window.scrollTo(0,0)}
function readDraft(){const n=document.getElementById('name'),no=document.getElementById('number');if(n){draft.name=n.value.slice(0,16);draft.number=E.clamp(Number(no.value)||9,1,99);}}
function dialog(title,html,confirmAction,confirmLabel='계속하기'){const el=document.getElementById('dialog');el.innerHTML='<h2 id="dialog-title">'+title+'</h2><div class="dialog-body">'+html+'</div><div class="dialog-actions">'+btn(confirmAction?'취소':'닫기','close','','outline')+(confirmAction?btn(confirmLabel,confirmAction,'',confirmAction==='confirm-delete-career'?'primary danger':'primary'):'')+'</div>';el.showModal()}
function guide(){
 dialog('축구 생활 · 게임 안내','<details class="guide-section disclosure" name="game-guide" open><summary>커리어 진행</summary><p>2000년, 중학교 3학년 15세로 시작합니다. 재능과 포지션, 아키타입을 정하면 첫 소속을 추첨합니다. 국내 명문 중학교 10곳에서 99%, 해외 유스에서 1% 확률입니다.</p><p>여름·겨울 이적시장을 기준으로 훈련과 경기를 진행합니다. 결과를 확인한 다음 진학이나 계약 제안을 고릅니다. 국내 중학교 졸업 때도 1% 확률로 해외 유스 제안이 옵니다.</p></details><details class="guide-section disclosure" name="game-guide"><summary>능력치와 경기 기록</summary><p>종합 능력은 포지션별로 세부 능력치에 가중치를 준 값입니다. 슈팅은 골 결정력·평정심·공격 위치선정, 패스는 패스·시야, 수비는 태클·가로채기·수비 이해도, 선방은 골키퍼 전용 능력이 중심입니다.</p><p>능력치가 높을수록 관련 플레이의 성공 확률이 높아집니다. 상대 전력, 동료, 출전 시간, 체력과 컨디션도 결과에 영향을 줍니다. 선방은 출전 중 상대 유효 슈팅에서 실점을 뺀 수로 기록합니다. 선발과 교체 출전도 구분합니다.</p><p>경기에서 실제로 사용한 능력은 조금씩 성장합니다. 반기 기록의 능력 변화에서 훈련·클럽 경기·A매치·노화로 인한 변화를 따로 확인할 수 있습니다.</p></details><details class="guide-section disclosure" name="game-guide"><summary>성장 · 부상 · 노화</summary><p>21세까지는 피지컬, 22~29세는 기술, 30세부터는 판단 능력이 중심입니다. 성장에는 잠재력, 재능, 집중 육성, 아키타입과 훈련 강도가 반영됩니다.</p><p>피지컬은 30세부터, 기술은 33세부터, 판단은 36세부터 서서히 감소합니다. 유지 훈련은 하락 속도를 늦춥니다. 2배 훈련은 피로와 부상 위험도 높아져 실제 성장이 두 배가 되지는 않습니다.</p><p>부상에는 회복 기간이 있습니다. 회복 전에는 경기에 나가지 못하고 훈련 성장량도 줄어듭니다. 약발 숙련도 85부터 양발을 활용할 수 있습니다.</p></details><details class="guide-section disclosure" name="game-guide"><summary>아키타입 · 플레이스타일</summary><p>재능 10종, 아키타입 13종, 플레이스타일 36종이 있습니다. 필요한 능력치를 모두 채우면 기본 플레이스타일을 자동으로 익힙니다.</p><p>아키타입 레벨 5에 플레이스타일+ 1칸, 레벨 10에 2칸이 열립니다. 기본 특성과 추가 능력 조건을 충족한 경로를 선수 화면에서 선택하세요.</p></details><details class="guide-section disclosure" name="game-guide"><summary>대회 · 대표팀</summary><p>유소년은 토너먼트로 진행하고, 프로는 대한민국·잉글랜드·이탈리아·프랑스·독일·스페인의 실제 구단에서 뜁니다. 프로 무대에서 대표팀에 발탁되면 클럽 진행을 멈추고 A매치 두 경기를 치릅니다. 대표팀 기록은 별도로 남습니다.</p><p>구단은 2000년과 2000/01 시즌을 기준으로 구성했습니다. 경기 결과는 새로 계산하며 실제 역사와 다릅니다. 유소년 대진·일정은 축약했으며 승강제, 대륙대항전, 대표팀 본선 대회는 포함하지 않습니다.</p></details><p class="help">기록은 브라우저에 저장됩니다. 기존 HTML 게임의 백업 파일도 설정에서 불러올 수 있습니다.</p>');
}
function menuIcon(id){
 const paths={home:'M3 11 12 3l9 8M5 10v11h5v-6h4v6h5V10',career:'M5 4h14v17H5zM9 4V2h6v2M9 9h6M9 13h6M9 17h4',player:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 22v-3a8 8 0 0 1 16 0v3',records:'M4 21V11h4v10M10 21V4h4v17M16 21v-8h4v8',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1zM12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8'};
 return '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[id]+'"/></svg>';
}
function settings(){
 return '<main class="content settings-page">'+title('FOOTBALL LIFE','설정')+'<section class="card"><h3>기록 보관</h3><p class="help">기록은 이 브라우저에 저장됩니다. 다른 기기나 사이트로 옮길 때는 백업 파일을 사용하세요.</p><div class="settings-actions">'+btn('기록 파일 저장','export','','outline full')+btn('기록 파일 불러오기','import','','outline full')+btn('보관 기록 관리','archives','','text-button full')+'</div></section><section class="card"><h3>화면</h3><button class="setting-toggle" data-action="toggle-motion" aria-pressed="'+reducedMotion+'"><span>움직임 줄이기</span><b>'+(reducedMotion?'켜짐':'꺼짐')+'</b></button><p class="help">화면 전환과 버튼 움직임을 줄입니다.</p></section><section class="card"><h3>축구 생활</h3><p class="help">Football Life · 1.0.0</p>'+btn('게임 안내','guide','','outline full')+btn('업데이트 내용','notice','','text-button full')+'<details class="disclosure sources-fold"><summary>참고 자료</summary><ul>'+E.SOURCES.map(([t,u])=>'<li><a target="_blank" rel="noopener noreferrer" href="'+u+'">'+esc(t)+'</a></li>').join('')+'</ul><p class="help">플레이스타일 아이콘은 FC27 클럽 빌더의 원본을 사용했습니다. 경기·성장·이적 결과는 게임 규칙으로 계산합니다.</p></details></section></main>';
}
function showNotice(){
 dialog('업데이트 · 1.0.0','<ul><li>슛·패스·수비·선방을 세부 능력치와 연결했습니다.</li><li>부상 회복 기간과 실제 출전 시간을 성장에 반영했습니다.</li><li>30세부터 신체 능력이 감소하고, 유지 훈련으로 하락을 늦출 수 있습니다.</li><li>기록 파일 불러오기를 추가했습니다.</li></ul>');
}
function confirmImport(){
 if(!pendingImport)return false;
 const before={game,archives,legacy},merged=FootballSave.merge(before,pendingImport);
 for(const g of [merged.game,...merged.archives])E.migrate(g);
 game=merged.game;archives=merged.archives;legacy=merged.legacy;
 if(!save()){({game,archives,legacy}=before);toast('저장하지 못해 불러오기를 취소했습니다.');return false;}
 pendingImport=null;document.getElementById('dialog').close();screen='home';tab='season';seasonView='training';toast('기록을 불러왔습니다.');return true;
}
async function readBackup(file){
 pendingImport=null;if(!file)return;
 try{
  if(file.size>15000000)throw Error('기록 파일은 15MB까지 불러올 수 있습니다.');
  const imported=FootballSave.parse(await file.text());pendingImport=imported;
  dialog('기록을 불러올까요?','<p>'+esc(imported.game?.player?.name||'보관 기록')+' · 보관된 인생 '+(imported.archives.length+imported.legacy.length)+'개</p><p>현재 선수는 보관 기록에 남기고, 파일에 있는 선수로 이어갑니다. 파일에 진행 중인 선수가 없으면 현재 선수는 유지합니다.</p>','confirm-import','불러오기');
 }catch(error){toast(error.message);}
}
function beginNew(){draft={name:'',number:9,pos:'ST',foot:'right',tactic:'balanced',focus:[]};deck=[];rerolls=2;screen='create';render()}
document.getElementById('dialog').addEventListener?.('close',()=>{pendingDeletion=null;pendingImport=null});
document.addEventListener('submit',event=>{if(event.target.id!=='creation')return;event.preventDefault();readDraft();if(!draft.name.trim())return;deck=E.candidates(draft.pos,freshSeed());revealed=false;selected=0;screen='talents';render()});
document.addEventListener('change',event=>{if(event.target.id==='backup-file'){readBackup(event.target.files[0]);event.target.value='';return;}if(event.target.id==='league-country'){leagueCountry=event.target.value;render(true)}});
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;let keep=false;try{
 if(a==='close'){pendingDeletion=null;pendingImport=null;document.getElementById('dialog').close();return}
 if(a==='delete-career'){requestCareerDeletion(el.dataset.source,Number(el.dataset.index));return}
 if(a==='confirm-delete-career'){if(confirmCareerDeletion())render();return}
 if(a==='guide'){guide();return}
 if(a==='notice'){showNotice();return}
 if(a==='settings')screen='settings';
 if(a==='player-menu'){screen='hub';tab='player';playerTab='attributes'}
 if(a==='import'){document.getElementById('backup-file').click();return}
 if(a==='confirm-import'){if(confirmImport())render();return}
 if(a==='toggle-motion'){reducedMotion=!reducedMotion;try{localStorage.setItem('football-life-preferences',JSON.stringify({reducedMotion}))}catch{}keep=true}
 if(a==='talent-guide'){talentGuide();return}
 if(a==='style-info'){styleInfo(v);return}
 if(a==='home')screen='home';
 if(a==='hub')screen='hub';
 if(a==='archives')screen='archives';
 if(a==='new'){if(game&&!game.retired){dialog('새로운 인생을 시작할까요?','<p>현재 커리어는 보관 기록에 남습니다. 새 선수는 2000년, 국내 중학교 또는 아주 드문 해외 유스에서 시작합니다.</p>','confirm-new');return}beginNew();return}
 if(a==='confirm-new'){document.getElementById('dialog').close();beginNew();return}
 if(a==='random'){readDraft();const r={seed:freshSeed()},positions=Object.keys(E.POS);draft.name=E.NAMES[E.int(r,0,E.NAMES.length-1)];draft.number=E.int(r,1,99);draft.pos=positions[E.int(r,0,positions.length-1)];draft.foot=E.rand(r)<.3?'left':'right';draft.focus=[];keep=true}
 if(a==='draft'){readDraft();if(el.dataset.key==='pos'&&E.POS[v]){draft.pos=v;draft.focus=E.normaliseFocus({pos:v},draft.focus)}else if(el.dataset.key==='foot'&&['left','right'].includes(v))draft.foot=v;keep=true}
 if(a==='edit'){screen='create'}
 if(a==='reveal'){revealed=true;keep=true}
 if(a==='candidate'){revealed=true;selected=Number(el.dataset.index);keep=true}
 if(a==='reroll'&&rerolls>0){deck=E.candidates(draft.pos,freshSeed(),deck);rerolls--;selected=0;revealed=true;keep=true;toast('새로운 유형과 능력치로 다시 뽑았습니다.')}
 if(a==='talents')screen='talents';
 if(a==='growth'){draft.archetypeId=deck[selected].archetypeId;screen='growth'}
 if(a==='archetype'){draft.archetypeId=v;keep=true}
 if(a==='tactic'&&E.TACTICS[v]){draft.tactic=v;keep=true}
 if(a==='focus'&&E.activeAttributes({pos:draft.pos}).includes(v)){if(draft.focus.includes(v))draft.focus=draft.focus.filter(k=>k!==v);else if(draft.focus.length<2)draft.focus.push(v);else toast('집중 육성은 2개까지 선택할 수 있습니다.');keep=true}
 if(a==='begin'){if(game)archives.push(game);game=E.create(draft,deck[selected],freshSeed());tab='season';seasonView='training';screen='hub';leagueCountry=game.country;save()}
 if(a==='tab'){tab=v;screen='hub'}
 if(a==='player-tab'){playerTab=v}
 if(a==='season-view'&&['training','schedule','traits'].includes(v)){seasonView=v;tab='season';screen='hub'}
 if(a==='market-next'&&game?.phase==='market'){game.marketStep='offers';save()}
 if(a==='market-back'&&game?.phase==='market'){game.marketStep='review';save()}
 if(a==='style-filter'){styleCategory=v;keep=true}
 if(a==='training'&&game.phase==='ready'&&!game.period.trained&&E.trainingOptions(game).some(t=>t.id===v)&&!(v==='weak'&&game.player.weakFoot>=100)){game.training=v;save();keep=true}
 if(a==='intensity'&&game.phase==='ready'&&!game.period.trained&&E.INTENSITIES[v]){game.intensity=v;save();keep=true}
 if(a==='advance'){E.advance(game);save();tab='season'}
 if(a==='international'){E.internationalMatch(game);save();keep=true}
 if(a==='return'){E.returnFromCamp(game);save();toast('대표팀 일정을 마쳤습니다. 소속팀 진행을 이어가세요.')}
 if(a==='offer'&&game?.phase==='market'&&game.marketStep==='offers'){if(E.accept(game,v)){seasonView='training';save();leagueCountry=game.country;toast('다음 반기가 시작됩니다.')}}
 if(a==='upgrade-plus'){if(!E.upgradePlus(game,v))toast('능력치와 레벨, 남은 강화 칸을 확인해 주세요.');else toast('플레이스타일+ 선택을 반영했습니다.');save();keep=true}
 if(a==='show-styles'){tab='player';playerTab='styles';screen='hub'}
 if(a==='show-plus'){tab='player';playerTab='archetype';screen='hub'}
 if(a==='retire'){dialog('은퇴하고 기록을 남길까요?','<p>현재 선수의 커리어를 마칩니다. 기록은 보관됩니다.</p>','confirm-retire');return}
 if(a==='confirm-retire'){document.getElementById('dialog').close();E.retire(game);save();tab='career'}
 if(a==='export'){const blob=new Blob([JSON.stringify({version:2,game,archives,legacy},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='football-life-기록.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return}
 render(keep);
 }catch(error){toast('진행을 완료하지 못했습니다. 기록을 백업하고 다시 시도해 주세요.');console.error(error)}});
render();
})();
